travis:
  secure:
    BINSTAR_TOKEN: yTHwXOdmTrXJ0MbbBb74jKlhoKxlgA7vLRcXIrkNv3zoc6jX+ZZ9My7zyZje+fgo9OIzSRvuryYWMFTIKNY4KgaxG2W3y+wySmhHYsgw+S1Y7PCWY8c1mQStVtZ+yirTiyckXFx/5OntCH4DM54luFxksrUP4n6F0pTOzIIcCyjpf404X0WQf09aMvb8yQlxk3R/zdiv2kEx98tQmk9A3BmmYJ9y6I4TGMwO5YMEL9i1fNZC+7vXvAMWdTPgowPg71Uf8K2xH5i0ReOjjsh8EOBEKsTUS6K43LCI+tZEenHdBxDJr5cKy8PhC2lhTkae2RhEqzyD0Xi0DuPwTYv+Jo67woE408nbZ6fhHkkkCSVVxCrng88DJckNzj2KAaNwDvix7LOj0+xRF6uC4lUINOG8VYYyhK7EBuq81G5L5DG0o6I0/p0BTytLjNnBN7sutiaJ9dTdedQbGZpqOy4N8X5zjPQa8icAKe2c+mL7Eqb49Y+C0ARIlDdBPPZif7cLcrDa92AMVxbQcg9VnR+m/sdD4V1Pd3DS46R8XHyrfl4uqvK+kwMJyLFy+kCRVlr4+5zciAnNKW097CO0wN+ICCBobkJqbaaOjDpN/Suenr+Vl9dbxaWN4aw5sKtNQTeNfZqoJj6KLMqZnaUpwOpTraKKqfyAa1GERGHSbT0XoCg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
